<?php
/**
	* this file displays an invoice, as generated by the Online-Store
	*
	* PHP version 5
	*
	* @category None
	* @package  None
	* @author   Kae Verens <kae@kvsites.ie>
	* @license  GPL 2.0
	* @link     None
	*/

require_once $_SERVER['DOCUMENT_ROOT'].'/ww.incs/basics.php';
require_once dirname(__FILE__).'/../api.php';

if (!isset($_REQUEST['id'])) {
	Core_quit();
}
$id=(int)$_REQUEST['id'];

echo OnlineStore_invoiceGet($id);
